name: Do something

on:
  workflow_dispatch:

jobs:
  do-something:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Checkout
      uses: actions/checkout@v2.3.2

    - name: Setup mocked mail
      run: echo "::add-path::${{ github.workspace }}/.github/bin"

    - run: echo "$PATH"

    - name: Try the mail thing
      run: |
        python3 -u -m smtpd -c DebuggingServer -d -n "localhost:8025" &> mail_log.txt & SMTP_PID="$!"
        sleep 5
        echo "SMTP process: $SMTP_PID"
        echo 'Maybe we could have a coupon day?' | mail -s 'Jurassic Park ticketing idea' -r 'donald.gennaro@ingen.com' runner
        sleep 10
        kill "$SMTP_PID"

    - name: Show the results
      run: |
        if [[ -f mail_log.txt ]]; then
          cat mail_log.txt
        else
          echo "mail_log.txt not found"
        fi
