name: Echo something

on:
  issues:
    types: [labeled]

jobs:
  echo-something:
    if: >-  # Testing multiline if
      always() &&
      contains(github.event.issue.labels.*.name, 'trigger-something')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Install mailx
      run: |
        sudo apt-get update
        sudo apt-get install -y bsd-mailx
        mail -s 'Welcome to bsd-mailx' runner@localhost <<< 'This email creates the mail directory'
        sleep 2
        mail # Check inbox
        which mail

    - name: Try the mail thing
      run: |
        export smtp='localhost:8025'
        smtp-sink -D 'mail_log.txt' -M 1 "$smtp" 1 & SMTP_PID="$!"
        sleep 2
        ps "$SMTP_PID"
        mail -s 'Jurassic Park ticketing suggestion' runner <<< 'Maybe we could have a coupon day?'
        sleep 5
        ps "$SMTP_PID"
        echo "(Note: 'Unexpected EOF on SMTP connection' message is expected)"

    - name: Show the results
      run: |
        if [[ -f mail_log.txt ]]; then
          cat mail_log.txt
        else
          echo "mail_log.txt not found"
        fi
        mail # Check inbox

