name: Echo something

on:
  issues:
    types: [labeled]

jobs:
  echo-something:
    if: >-  # Testing multiline if
      always() &&
      contains(github.event.issue.labels.*.name, 'trigger-something')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - run: echo "Well, it worked"
