name: Do something

on:
  issues:
    types: [labeled]

jobs:
  do-something:
    if: >-  # Testing multiline if
      always() &&
      contains(github.event.issue.labels.*.name, 'trigger-something')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # - name: Install SMTP stuff
    #   run: |
    #     python3 -m pip install smtp

    - name: Setup mocked mail
      run: echo "::add-path::${{ github.workspace }}/.github/bin"

    - run: echo "$PATH"

    - name: Try the mail thing
      run: |
        python3 -u -m smtpd -c DebuggingServer -d -n "$smtp" &> mail_log.txt & SMTP_PID="$!"
        sleep 5
        echo "SMTP process: $SMTP_PID"
        mail -s 'Jurassic Park ticketing idea' runner <<< 'Maybe we could have a coupon day?'
        sleep 10
        kill "$SMTP_PID"

    - name: Show the results
      run: |
        if [[ -f mail_log.txt ]]; then
          cat mail_log.txt
        else
          echo "mail_log.txt not found"
        fi
